version: '3.8'

services:
  spark-iceberg:
    image: spark-master
    container_name: spark-iceberg
    build:
      context: ./
      args:
        SPARK_DEFAULTS_CONF: spark-defaults.conf
    entrypoint: [ './entrypoint.sh', 'master' ]
    env_file:
      - .env
    volumes:
      - ../volumes/notebooks:/home/iceberg/notebooks
      - ../volumes/data:/opt/spark/data
      - ../volumes/spark_apps:/opt/spark/apps
      - ../volumes/spark-logs:/opt/spark/spark-events
    ports:
      - '8888:8888'
      - '8080:8080'
      - '10000:10000'
      - '10001:10001'
    networks:
      - iceberg_net

  spark-worker:
    container_name: spark-worker
    image: spark-master
    entrypoint: [ './entrypoint.sh', 'worker' ]
    depends_on:
      - spark-iceberg
    env_file:
      - .env
    volumes:
      - ../volumes/data:/opt/spark/data
      - ../volumes/spark_apps:/opt/spark/apps
      - ../volumes/logs_worker:/opt/spark/logs
      - ../spark-logs:/opt/spark/spark-events
    ports:
      - '8081:8081'
    networks:
      - iceberg_net

  spark-history-server:
    container_name: spark-history
    image: spark-master
    entrypoint: [ './entrypoint.sh', 'history' ]
    depends_on:
      - spark-iceberg
    env_file:
      - .env
    volumes:
      - ../volumes/spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
    networks:
      - iceberg_net

networks:
  iceberg_net:
    external: true
