services:
  minio-principal:
    image: minio/minio:latest
    container_name: minio-principal
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server --console-address ":9001" /data
    networks:
      iceberg_net:
        aliases:
          - lakehouse.minio-principal
    volumes:
      - ../volumes/minio-principal-data:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-principal-data:


networks:
  iceberg_net:
    external: true
