version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../volumes/grafana-data:/var/lib/grafana
    networks:
      - iceberg_net

volumes:
  grafana-data:


networks:
  iceberg_net:
    external: true
