version: '3.8'

services:
  pg-catalog:
    image: postgres:15-alpine
    container_name: pg_catalog
    networks:
      - iceberg_net
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "iceberg" ]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/catalog_data:/var/lib/postgresql/data

networks:
  iceberg_net:
    external: true
